export const categories = [
  { slug: "olive-oils", label: "Olive Oils", icon: "🫒" },
  { slug: "infused-oils", label: "Infused Olive Oils", icon: "🌿" },
  { slug: "vinegars", label: "Fruit Vinegars", icon: "🍇" },
  { slug: "salts", label: "Artisan Salts", icon: "🧂" },
  { slug: "wines", label: "Fruit Wines", icon: "🍷" },
  { slug: "liqueurs", label: "Liqueurs", icon: "🥃" },
  { slug: "baskets", label: "Gourmet Baskets", icon: "🧺" },
  { slug: "gifts", label: "Gift Boxes", icon: "🎁" },
];

export const products = [
  {
    id: 1,
    slug: "arbequina-evoo",
    name: "Arbequina Extra Virgin Olive Oil",
    category: "olive-oils",
    price: 34.99,
    origin: "Catalonia, Spain",
    description:
      "Cold-pressed from hand-picked Arbequina olives. Notes of fresh-cut grass, ripe tomato, and a gentle peppery finish. Our flagship oil.",
    details: ["500ml bottle", "Harvest: October 2024", "Acidity < 0.2%", "First cold press"],
    featured: true,
  },
  {
    id: 2,
    slug: "picual-evoo",
    name: "Picual Premium Olive Oil",
    category: "olive-oils",
    price: 38.99,
    origin: "Jaén, Andalusia",
    description:
      "Robust and full-bodied with a distinctive peppery kick. Ideal for drizzling, cooking, and pairing with aged cheeses.",
    details: ["500ml bottle", "Harvest: November 2024", "Acidity < 0.3%", "Single estate"],
    featured: true,
  },
  {
    id: 3,
    slug: "garlic-infused-oil",
    name: "Garlic Infused Olive Oil",
    category: "infused-oils",
    price: 29.99,
    origin: "Seville, Spain",
    description:
      "Slow-infused with roasted Spanish garlic. A pantry essential that transforms every dish it touches.",
    details: ["250ml bottle", "Natural infusion", "No additives", "Vegetarian"],
    featured: false,
  },
  {
    id: 4,
    slug: "lemon-infused-oil",
    name: "Lemon Infused Olive Oil",
    category: "infused-oils",
    price: 29.99,
    origin: "Valencia, Spain",
    description:
      "Bright Valencian lemons cold-pressed together with Arbequina olives for an intense citrus-oil fusion.",
    details: ["250ml bottle", "Cold co-pressed", "Zesty & fresh", "Award-winning"],
    featured: true,
  },
  {
    id: 5,
    slug: "pedro-ximenez-vinegar",
    name: "Pedro Ximénez Sherry Vinegar",
    category: "vinegars",
    price: 24.99,
    origin: "Jerez, Spain",
    description:
      "Aged 10 years in American oak barrels. Rich, sweet, and complex with notes of dried fruit and caramel.",
    details: ["250ml bottle", "Aged 10 years", "DOP Certified", "Denomination of Origin"],
    featured: true,
  },
  {
    id: 6,
    slug: "raspberry-vinegar",
    name: "Raspberry Fruit Vinegar",
    category: "vinegars",
    price: 19.99,
    origin: "Navarra, Spain",
    description:
      "Made from sun-ripened Navarran raspberries. Perfect for salads, marinades, and creative cocktails.",
    details: ["250ml bottle", "Natural fermentation", "No sulfites", "Fruit-forward"],
    featured: false,
  },
  {
    id: 7,
    slug: "fleur-de-sel",
    name: "Fleur de Sel de Cadiz",
    category: "salts",
    price: 16.99,
    origin: "Cádiz, Spain",
    description:
      "Hand-harvested from the Atlantic salt pans of Cádiz. Delicate, moist flakes with a subtle oceanic minerality.",
    details: ["200g jar", "Hand-harvested", "Unrefined", "Mineral-rich"],
    featured: true,
  },
  {
    id: 8,
    slug: "smoked-salt",
    name: "Iberian Smoked Sea Salt",
    category: "salts",
    price: 18.99,
    origin: "Extremadura, Spain",
    description:
      "Slow-smoked over oak and rosemary for 48 hours. Extraordinary depth of flavor for grilling and charcuterie.",
    details: ["150g jar", "Cold smoked 48h", "Oak & rosemary", "Artisan produced"],
    featured: false,
  },
  {
    id: 9,
    slug: "muscatel-wine",
    name: "Muscatel Fruit Wine",
    category: "wines",
    price: 44.99,
    origin: "Málaga, Spain",
    description:
      "A luscious dessert wine from sun-dried Muscatel grapes. Honey, apricot, and orange blossom on the palate.",
    details: ["750ml bottle", "17% ABV", "Serve chilled", "Pairs with desserts"],
    featured: true,
  },
  {
    id: 10,
    slug: "pomegranate-wine",
    name: "Pomegranate Fruit Wine",
    category: "wines",
    price: 36.99,
    origin: "Elche, Spain",
    description:
      "Fermented from hand-selected Elche pomegranates. Vibrant ruby color with tart berry complexity.",
    details: ["750ml bottle", "13.5% ABV", "Semi-sweet", "Limited batch"],
    featured: false,
  },
  {
    id: 11,
    slug: "herbs-liqueur",
    name: "Hierbas Ibicencas Liqueur",
    category: "liqueurs",
    price: 52.99,
    origin: "Ibiza, Spain",
    description:
      "The iconic herbal liqueur of Ibiza. A secret blend of 30+ Mediterranean herbs macerated in neutral spirit.",
    details: ["700ml bottle", "25% ABV", "30+ botanicals", "Traditional recipe"],
    featured: true,
  },
  {
    id: 12,
    slug: "saffron-liqueur",
    name: "Azafrán Saffron Liqueur",
    category: "liqueurs",
    price: 68.99,
    origin: "La Mancha, Spain",
    description:
      "An extraordinary liqueur made with La Mancha DOP saffron. Golden color, floral aroma, warming finish.",
    details: ["500ml bottle", "20% ABV", "DOP Saffron", "Ultra premium"],
    featured: true,
  },
  {
    id: 13,
    slug: "deluxe-basket",
    name: "Gourmet Spain Basket",
    category: "baskets",
    price: 129.99,
    origin: "Various regions",
    description:
      "A curated selection of our finest products. Includes EVOO, sherry vinegar, artisan salts, and signature olive spread.",
    details: ["6 products", "Gift-wrapped", "Free message card", "Free shipping"],
    featured: true,
  },
  {
    id: 14,
    slug: "luxury-gift-box",
    name: "Luxury Black Gift Box",
    category: "gifts",
    price: 189.99,
    origin: "Various regions",
    description:
      "Our most prestigious gift presentation. Premium black box with gold ribbon, housing our award-winning collection.",
    details: ["8 products", "Black & gold box", "Satin ribbon", "Personalized card"],
    featured: true,
  },
];

export const recipes = [
  {
    id: 1,
    slug: "burrata-lemon-oil",
    title: "Burrata with Lemon Oil & Heirloom Tomatoes",
    category: "Starters",
    time: "10 min",
    difficulty: "Easy",
    product: "Lemon Infused Olive Oil",
    description: "A stunning summer starter that lets our lemon oil shine.",
  },
  {
    id: 2,
    slug: "roasted-vegetables-rosemary",
    title: "Roasted Vegetables with Rosemary Oil",
    category: "Mains",
    time: "45 min",
    difficulty: "Easy",
    product: "Arbequina EVOO",
    description: "Seasonal vegetables roasted to perfection in our premium oils.",
  },
  {
    id: 3,
    slug: "grilled-seafood-pepper-oil",
    title: "Grilled Seafood with Spicy Pepper Oil",
    category: "Mains",
    time: "30 min",
    difficulty: "Medium",
    product: "Picual Premium Oil",
    description: "Mediterranean-style grilled seafood elevated with our bold Picual.",
  },
  {
    id: 4,
    slug: "heirloom-tomatoes-artisan-salt",
    title: "Heirloom Tomatoes with Artisan Salt",
    category: "Sides",
    time: "5 min",
    difficulty: "Easy",
    product: "Fleur de Sel de Cadiz",
    description: "The simplest showcase of our hand-harvested fleur de sel.",
  },
  {
    id: 5,
    slug: "arugula-fig-vinegar",
    title: "Arugula Salad with Fig Vinegar",
    category: "Salads",
    time: "10 min",
    difficulty: "Easy",
    product: "Pedro Ximénez Sherry Vinegar",
    description: "A refined salad with peppery arugula and our aged sherry vinegar.",
  },
];

export const distributorStats = [
  { value: "500+", label: "Distributor Partners" },
  { value: "28", label: "U.S. States Served" },
  { value: "15+", label: "Years of Excellence" },
  { value: "200+", label: "SKUs Available" },
];
