export type Product = {
  slug: string;
  name: string;
  nameEs: string;
  category: string;
  image: string;
  gallery?: string[];
  description: string;
  longDescription: string;
  producer: string;
  origin: string;
  pairings: string[];
  price: number; // USD
};

export const allProducts: Product[] = [
  // ── Olive Oils ──────────────────────────────────────────────
  {
    slug: "garlic-olive-oil",
    name: "Garlic Olive Oil",
    nameEs: "Aceite de Ajo",
    category: "olive-oils",
    image: "/products/aceite-ajo.jpg",
    description: "Extra virgin olive oil delicately infused with fresh Spanish garlic. Rich, savory, and versatile, ideal for finishing, dipping, and cooking.",
    longDescription: "Príncipe Azahar's Garlic Olive Oil is crafted from premium extra virgin olive oil cold-pressed from hand-picked Spanish olives, then gently infused with fresh ajo (garlic) from the fertile fields of Altea. The result is a deeply aromatic, savory oil with a smooth garlic warmth that enhances any dish without overpowering it. Use it to finish grilled meats, drizzle over bruschetta, toss with pasta, or as a base for vinaigrettes.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Grilled meats", "Crusty bread", "Pasta", "Roasted vegetables", "Bruschetta"],
    price: 259,
  },
  {
    slug: "chili-olive-oil",
    name: "Chili Olive Oil",
    nameEs: "Aceite de Guindillas",
    category: "olive-oils",
    image: "/products/aceite-guindillas.jpg",
    description: "Extra virgin olive oil infused with Spanish guindilla peppers. A warm, gentle heat that elevates any dish with bold character.",
    longDescription: "Made with the finest extra virgin olive oil from Altea and infused with whole guindilla peppers, Spain's beloved small chili, this oil delivers a lingering, pleasant heat without harshness. It's the finishing touch that turns a simple dish into something memorable. Exceptional drizzled over pizza, grilled fish, eggs, or stirred into soups.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Pizza", "Grilled fish", "Eggs", "Soups", "Cheese boards"],
    price: 259,
  },
  {
    slug: "lemon-olive-oil",
    name: "Lemon Olive Oil",
    nameEs: "Aceite de Limón",
    category: "olive-oils",
    image: "/products/aceite-limon.jpg",
    description: "Bright, citrusy extra virgin olive oil cold-pressed with fresh Spanish lemons. Perfect for salads, fish, and Mediterranean cuisine.",
    longDescription: "This vibrant olive oil is produced by cold-pressing ripe Spanish olives together with fresh lemons from the Mediterranean coast, capturing an intensely fresh citrus flavor in every drop. Light, fragrant, and elegant, it's exceptional on salads, drizzled over grilled fish, stirred into yogurt, or used to finish a delicate pasta.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Salads", "Grilled fish", "Seafood", "Yogurt", "Asparagus"],
    price: 259,
  },
  {
    slug: "rosemary-olive-oil",
    name: "Rosemary Olive Oil",
    nameEs: "Aceite de Romero",
    category: "olive-oils",
    image: "/products/aceite-romero.jpg",
    description: "Extra virgin olive oil infused with fresh rosemary from the hills of Altea. Fragrant, herbaceous, and deeply Spanish.",
    longDescription: "Wild rosemary grows abundantly in the hills above Altea, and Príncipe Azahar captures its essence by infusing premium extra virgin olive oil with freshly harvested sprigs. The result is a beautifully aromatic oil, piney, herbaceous, and warm, that is extraordinary on roasted lamb, focaccia, roasted potatoes, and grilled poultry.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Roasted lamb", "Focaccia", "Roasted potatoes", "Grilled poultry", "Mushrooms"],
    price: 259,
  },
  {
    slug: "truffle-olive-oil",
    name: "Truffle Olive Oil",
    nameEs: "Aceite de Trufa",
    category: "olive-oils",
    image: "/products/aceite-trufa.jpg",
    description: "Luxurious extra virgin olive oil infused with black truffle. An extraordinary ingredient for those who appreciate the finest flavors.",
    longDescription: "A true luxury product, Príncipe Azahar's Truffle Olive Oil blends exceptional extra virgin olive oil with the unmistakable earthy elegance of black truffle. Just a few drops transform scrambled eggs, risotto, pasta, or pizza into a fine dining experience. This is the definitive finishing oil for those who demand the extraordinary.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Scrambled eggs", "Risotto", "Pasta", "Pizza", "Beef tartare"],
    price: 259,
  },

  // ── Salts ────────────────────────────────────────────────────
  {
    slug: "garlic-salt",
    name: "Garlic Salt",
    nameEs: "Sal Ajo",
    category: "salts",
    image: "/products/sal-ajo.jpg",
    gallery: ["/products/sal-ajo.jpg", "/products/sal-ajo-2.jpg"],
    description: "Natural flake sea salt from Altea blended with aromatic Spanish garlic. A finishing salt that adds depth to any dish.",
    longDescription: "Hand-harvested natural flake sea salt from the Spanish coastline, delicately blended with dried Spanish garlic. This is the finishing salt you reach for when you want savory depth without sharpness. Exceptional on grilled meats, roasted vegetables, pasta, or simply on buttered bread.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Grilled meats", "Roasted vegetables", "Pasta", "Buttered bread", "Soups"],
    price: 119,
  },
  {
    slug: "bbq-salt",
    name: "BBQ Salt",
    nameEs: "Sal Barbacoa",
    category: "salts",
    image: "/products/sal-barbacoa.jpg",
    gallery: ["/products/sal-barbacoa.jpg", "/products/sal-barbacoa-2.jpg"],
    description: "Smoky, bold artisan salt crafted for grilling. A must-have for meats, vegetables, and outdoor cooking.",
    longDescription: "Crafted for the grill, this bold artisan flake salt combines natural sea salt from Altea with smoky barbecue spices. Whether you're seasoning a steak, finishing ribs, or sprinkling over corn on the cob, Sal Barbacoa delivers a deep, smoky complexity that takes grilling to a new level.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Steak", "Ribs", "Corn", "Grilled vegetables", "Burgers"],
    price: 119,
  },
  {
    slug: "white-salt",
    name: "White Salt",
    nameEs: "Sal Blanca",
    category: "salts",
    image: "/products/sal-blanca.jpg",
    gallery: ["/products/sal-blanca.jpg", "/products/sal-blanca-2.jpg"],
    description: "Pure, hand-harvested natural flake sea salt from the Spanish coastline. Clean, bright, and exceptionally versatile.",
    longDescription: "The purest expression of Spanish sea salt, hand-harvested natural flake salt from the Mediterranean coast. Bright, clean, and mineral, Sal Blanca is the essential finishing salt for any kitchen. Its delicate flakes dissolve on the tongue and enhance the natural flavors of every ingredient it touches.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Everything", "Salads", "Fish", "Butter", "Chocolate"],
    price: 119,
  },
  {
    slug: "onion-salt",
    name: "Onion Salt",
    nameEs: "Sal Cebolla",
    category: "salts",
    image: "/products/sal-cebolla.jpg",
    gallery: ["/products/sal-cebolla.jpg", "/products/sal-cebolla-2.jpg"],
    description: "Artisan flake salt infused with sweet Spanish onion. Delicate yet full-flavored, wonderful on meats, soups, and vegetables.",
    longDescription: "Naturally sweet Spanish onion is carefully dried and blended with hand-harvested flake sea salt from Altea, creating a finishing salt with a subtle sweetness and savory complexity. Beautiful on grilled chicken, soups, potato dishes, and anywhere you want a gentle onion note without the bite of fresh onion.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Grilled chicken", "Soups", "Potato dishes", "Onion rings", "Savory pastries"],
    price: 119,
  },
  {
    slug: "curry-salt",
    name: "Curry Salt",
    nameEs: "Sal Curry",
    category: "salts",
    image: "/products/sal-curry.jpg",
    gallery: ["/products/sal-curry.jpg", "/products/sal-curry-2.jpg"],
    description: "Natural sea salt blended with warm curry spices. A distinctive, aromatic finishing salt with golden color and exotic character.",
    longDescription: "Spanish artisan sea salt meets aromatic curry spices in this golden, warmly exotic finishing salt. Sal Curry adds a sophisticated touch to grilled fish, roasted cauliflower, rice dishes, and yogurt dips. Its vibrant color and complex aroma make it as beautiful to present as it is to taste.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Grilled fish", "Cauliflower", "Rice dishes", "Yogurt dips", "Roasted chickpeas"],
    price: 119,
  },
  {
    slug: "lemon-salt",
    name: "Lemon Salt",
    nameEs: "Sal Limón",
    category: "salts",
    image: "/products/sal-limon.jpg",
    gallery: ["/products/sal-limon.jpg", "/products/sal-limon-2.jpg"],
    description: "Bright, citrus-infused artisan flake salt. Exceptional on seafood, salads, and fresh vegetables.",
    longDescription: "Spanish Mediterranean lemon zest is carefully blended with hand-harvested flake sea salt from the Altea coast, producing a bright, citrusy finishing salt that lifts the flavor of everything it touches. Sal Limón is exceptional on grilled shrimp, oysters, fresh salads, avocado, and grilled fish.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Grilled shrimp", "Oysters", "Salads", "Avocado", "Grilled fish"],
    price: 119,
  },
  {
    slug: "mint-salt",
    name: "Mint Salt",
    nameEs: "Sal Menta",
    category: "salts",
    image: "/products/sal-menta.jpg",
    gallery: ["/products/sal-menta.jpg", "/products/sal-menta-2.jpg"],
    description: "Refreshing natural flake salt delicately blended with fresh mint. Unique and elegant, ideal for lamb, desserts, and cocktails.",
    longDescription: "One of the most surprising and elegant products in the Princesa Azahar collection, fresh mint is blended with hand-harvested sea salt from the Spanish coast, producing a cooling, aromatic finishing salt unlike anything else. Exceptional on lamb chops, fresh mango, strawberries, cocktails, and fine chocolate. Also the star ingredient in Sasha's Salted Mangos.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Lamb chops", "Fresh mango", "Strawberries", "Cocktails", "Dark chocolate"],
    price: 119,
  },
  {
    slug: "orange-salt",
    name: "Orange Salt",
    nameEs: "Sal Naranja",
    category: "salts",
    image: "/products/sal-naranja.jpg",
    gallery: ["/products/sal-naranja.jpg", "/products/sal-naranja-2.jpg"],
    description: "Artisan sea salt infused with Spanish orange zest. Sweet, citrusy, and surprising, a favorite for duck, fish, and chocolate.",
    longDescription: "Fragrant Spanish orange zest is blended with natural flake sea salt from Altea to create this vibrant, citrusy finishing salt. Sal Naranja is especially beautiful on duck breast, salmon, dark chocolate desserts, and fresh fruit. The combination of sweet orange and flaky sea salt creates an unexpected elegance on the palate.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Duck breast", "Salmon", "Dark chocolate", "Fresh fruit", "Scallops"],
    price: 119,
  },
  {
    slug: "black-salt",
    name: "Black Salt",
    nameEs: "Sal Negra",
    category: "salts",
    image: "/products/sal-negra.jpg",
    gallery: ["/products/sal-negra.jpg", "/products/sal-negra-2.jpg"],
    description: "Striking jet-black artisan salt with a mineral richness. A dramatic finishing salt for elegant presentations.",
    longDescription: "Sal Negra is a visually stunning, jet-black finishing salt with a deep mineral character that enhances both the flavor and presentation of any dish. Its dramatic appearance makes it perfect for upscale plating, on white fish, eggs, sushi, caprese salad, or fine chocolate. An exceptional gifting product for those who appreciate the extraordinary.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["White fish", "Eggs", "Sushi", "Caprese salad", "Dark chocolate"],
    price: 119,
  },
  {
    slug: "oregano-salt",
    name: "Oregano Salt",
    nameEs: "Sal Orégano",
    category: "salts",
    image: "/products/sal-oregano.jpg",
    gallery: ["/products/sal-oregano.jpg", "/products/sal-oregano-2.jpg"],
    description: "Mediterranean flake salt blended with wild Spanish oregano. Classic, aromatic, and essential for any Spanish kitchen.",
    longDescription: "Wild Mediterranean oregano, the backbone of Spanish and Greek cuisine, is blended with hand-harvested flake sea salt from Altea. Sal Orégano is the essential finishing salt for grilled meats, tomato dishes, pizza, marinades, and anything that calls for the warm, herbaceous flavor of true Mediterranean oregano.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Grilled meats", "Tomato dishes", "Pizza", "Marinades", "Feta cheese"],
    price: 119,
  },
  {
    slug: "paprika-salt",
    name: "Paprika Salt",
    nameEs: "Sal Pimentón",
    category: "salts",
    image: "/products/sal-pimenton.jpg",
    gallery: ["/products/sal-pimenton.jpg", "/products/sal-pimenton-2.jpg"],
    description: "Rich artisan salt infused with Spanish smoked paprika (pimentón). Deeply smoky, vibrant, and unmistakably Iberian.",
    longDescription: "Spanish pimentón, the iconic smoked paprika that defines the flavor of Spain, is blended with natural flake sea salt from Altea. The result is a deeply smoky, vivid red finishing salt that is unmistakably Iberian. Essential for Patatas Bravas, grilled meats, eggs, and anywhere you want the soul of Spanish cooking.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Patatas Bravas", "Grilled meats", "Eggs", "Hummus", "Roasted peppers"],
    price: 119,
  },
  {
    slug: "rose-salt",
    name: "Rose Salt",
    nameEs: "Sal Rosas",
    category: "salts",
    image: "/products/sal-rosas.jpg",
    gallery: ["/products/sal-rosas.jpg", "/products/sal-rosas-2.jpg"],
    description: "Delicate pink flake salt with subtle floral notes. Beautiful in presentation and gentle in flavor, a truly refined finishing salt.",
    longDescription: "Sal Rosas is one of the most visually beautiful and flavor-nuanced salts in the Princesa Azahar collection. Delicate pink flakes carry subtle floral notes that pair exquisitely with fine chocolate, fresh berries, champagne reductions, and white fish. As stunning in presentation as it is in taste, an exceptional gifting salt.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Dark chocolate", "Fresh berries", "White fish", "Champagne dishes", "Butter"],
    price: 119,
  },
  {
    slug: "rosemary-salt",
    name: "Rosemary Salt",
    nameEs: "Sal Romero",
    category: "salts",
    image: "/products/sal-romero.jpg",
    gallery: ["/products/sal-romero.jpg", "/products/sal-romero-2.jpg"],
    description: "Natural sea salt blended with fragrant rosemary from Altea. Perfect for roasted meats, potatoes, and rustic breads.",
    longDescription: "Wild rosemary harvested from the hills of Altea is dried and blended with hand-harvested flake sea salt from the Mediterranean coast. Sal Romero is deeply fragrant, herbaceous, and earthy, essential for roasted lamb, focaccia, roasted potatoes, and slow-cooked meats. A cornerstone of Spanish and Mediterranean cooking.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Roasted lamb", "Focaccia", "Roasted potatoes", "Slow-cooked meats", "Olive oil dips"],
    price: 119,
  },
  {
    slug: "wild-salt",
    name: "Wild Salt",
    nameEs: "Sal Salvaje",
    category: "salts",
    image: "/products/sal-salvaje.jpg",
    gallery: ["/products/sal-salvaje.jpg", "/products/sal-salvaje-2.jpg"],
    description: "Unrefined wild-harvested flake sea salt from the Spanish coast. Pure, mineral-rich, and extraordinary.",
    longDescription: "Sal Salvaje is hand-harvested from untouched salt flats along the Spanish Mediterranean coast, unrefined, unprocessed, and rich in natural trace minerals. Its large, irregular flakes carry the full flavor of the sea. Use it as a premium finishing salt on virtually anything, from rare steaks to fresh salads to artisan bread.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Rare steak", "Fresh salads", "Artisan bread", "Butter", "Grilled fish"],
    price: 119,
  },
  {
    slug: "liquid-wild-salt",
    name: "Liquid Wild Salt",
    nameEs: "Sal Salvaje Líquida",
    category: "salts",
    image: "/products/sal-salvaje-liquida.jpg",
    gallery: ["/products/sal-salvaje-liquida.jpg", "/products/sal-salvaje-liquida-2.jpg"],
    description: "Wild sea salt in liquid form, an innovative way to season with precision and elegance. Perfect for finishing and marinades.",
    longDescription: "An innovative take on Spain's finest sea salt, Sal Salvaje dissolved into a pure liquid solution, allowing you to season with extraordinary precision. A few drops on any dish provides perfect seasoning without texture or visible crystals. Ideal for marinades, vinaigrettes, cocktails, desserts, and anywhere subtle, even seasoning is essential.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Marinades", "Vinaigrettes", "Cocktails", "Desserts", "Ceviche"],
    price: 119,
  },
  {
    slug: "tomato-salt",
    name: "Tomato Salt",
    nameEs: "Sal Tomate",
    category: "salts",
    image: "/products/sal-tomate.jpg",
    gallery: ["/products/sal-tomate.jpg", "/products/sal-tomate-2.jpg"],
    description: "Vibrant artisan salt infused with sun-ripened Spanish tomato. Exceptional on eggs, salads, grilled meats, and fresh mozzarella.",
    longDescription: "Sun-ripened Spanish tomatoes are dried and blended with hand-harvested flake sea salt from Altea, creating a vibrant, savory finishing salt with the concentrated sweetness of ripe Mediterranean tomato. Sal Tomate is extraordinary on fresh mozzarella, eggs, pan con tomate, grilled fish, and anything in need of a bright, umami-rich finish.",
    producer: "Princesa Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Fresh mozzarella", "Eggs", "Pan con tomate", "Grilled fish", "Avocado toast"],
    price: 119,
  },

  // ── Vinegars ─────────────────────────────────────────────────
  {
    slug: "pomegranate-vinegar",
    name: "Pomegranate Vinegar",
    nameEs: "Vinagre Granada",
    category: "vinegars",
    image: "/products/vinagre-granada.jpg",
    gallery: ["/products/vinagre-granada.jpg", "/products/vinagre-granada-2.jpg"],
    description: "Aged Spanish vinegar with the rich, jewel-like flavor of pomegranate. A striking ingredient for dressings, reductions, and gourmet cooking.",
    longDescription: "Crafted in Altea using traditional methods, this artisan vinegar is aged with the deep, rich flavor of Spanish pomegranate. Its beautiful ruby complexity, sweet, tart, and full-bodied, makes it exceptional in salad dressings, reductions for duck or lamb, cheese pairings, and cocktails. A dramatic and distinctive gourmet ingredient.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Duck", "Lamb", "Cheese boards", "Salad dressings", "Cocktails"],
    price: 259,
  },
  {
    slug: "fig-vinegar",
    name: "Fig Vinegar",
    nameEs: "Vinagre Higos",
    category: "vinegars",
    image: "/products/vinagre-higos.jpg",
    gallery: ["/products/vinagre-higos.jpg", "/products/vinagre-higos-2.jpg"],
    description: "Slow-aged vinegar with the lush sweetness of Spanish figs. Beautiful in salads, cheese pairings, and charcuterie.",
    longDescription: "Ripe Spanish figs lend their lush, honeyed sweetness to this slow-aged artisan vinegar from Altea. Vinagre Higos is rich, complex, and beautifully balanced, not too sharp, not too sweet. It elevates any cheese board, pairs brilliantly with Iberian charcuterie, and transforms a simple salad into something extraordinary.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Cheese boards", "Iberian charcuterie", "Salads", "Foie gras", "Walnuts"],
    price: 259,
  },
  {
    slug: "lemon-vinegar",
    name: "Lemon Vinegar",
    nameEs: "Vinagre Limón",
    category: "vinegars",
    image: "/products/vinagre-limon.jpg",
    gallery: ["/products/vinagre-limon.jpg", "/products/vinagre-limon-2.jpg"],
    description: "Bright, tangy vinegar with vibrant Spanish lemon. A refreshing complement to seafood, greens, and light Mediterranean dishes.",
    longDescription: "Spanish Mediterranean lemons are the heart of this bright, tangy artisan vinegar from Altea. Vivid and refreshing, Vinagre Limón is the ideal dressing for grilled seafood, green salads, and any light Mediterranean dish where you want citrus complexity beyond simple lemon juice. Also extraordinary in fish marinades and ceviches.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Grilled seafood", "Green salads", "Ceviche", "Fish marinades", "Asparagus"],
    price: 259,
  },
  {
    slug: "orange-vinegar",
    name: "Orange Vinegar",
    nameEs: "Vinagre Naranja",
    category: "vinegars",
    image: "/products/vinagre-naranja.jpg",
    gallery: ["/products/vinagre-naranja.jpg", "/products/vinagre-naranja-2.jpg"],
    description: "Aged 11 years. A Reserva-grade artisan vinegar with the warm, citrus complexity of Spanish orange. 200ml · 4.9° AC.",
    longDescription: "Aged for 11 years using traditional Reserva methods in Altea, this exceptional orange vinegar represents the pinnacle of Spanish artisan vinegar-making. The extended aging process develops extraordinary depth, layers of citrus warmth, natural sweetness, and mellow acidity. Vinagre Naranja is 200ml of pure Spanish culinary heritage.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain · Reserva 11 años · 200ml",
    pairings: ["Duck", "Venison", "Cheese", "Reduction sauces", "Strawberries"],
    price: 259,
  },
  {
    slug: "vanilla-vinegar",
    name: "Vanilla Vinegar",
    nameEs: "Vinagre Vainilla",
    category: "vinegars",
    image: "/products/vinagre-vainilla.jpg",
    gallery: ["/products/vinagre-vainilla.jpg", "/products/vinagre-vainilla-2.jpg"],
    description: "An exquisite aged vinegar with delicate vanilla warmth. Extraordinary on desserts, strawberries, and fine cheese.",
    longDescription: "The most unexpected and surprising product in the Príncipe Azahar collection, natural vanilla is aged into artisan Spanish vinegar, producing something that defies category. Vinagre Vainilla is silky, warm, and gently sweet, with just enough acidity to balance. It is extraordinary drizzled over fresh strawberries, ice cream, panna cotta, aged cheese, and fine chocolate.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Fresh strawberries", "Ice cream", "Panna cotta", "Aged cheese", "Dark chocolate"],
    price: 259,
  },

  // ── Orange Wine ───────────────────────────────────────────────
  {
    slug: "orange-wine",
    name: "Orange Wine",
    nameEs: "Vino de Naranja",
    category: "wine",
    image: "/products/vino-naranja.jpg",
    description: "BSG Príncipe Azahar Orange Wine. A signature expression from Altea, elegant, golden, and uniquely Spanish. 500ml · 12.5% vol.",
    longDescription: "Vino de Naranja is a signature Spanish orange wine produced by Bodegas Sendra González in Altea, a traditional style that has been made along Spain's Mediterranean coast for centuries. Beautifully golden, with warm citrus aromatics, a smooth texture, and a distinctive character that is unlike any conventional wine. Serve chilled as an aperitif or alongside seafood, charcuterie, and aged cheeses. 500ml · 12.5% vol.",
    producer: "BSG · Bodegas Sendra González",
    origin: "Altea, Spain · 500ml · 12.5% vol.",
    pairings: ["Seafood", "Charcuterie", "Aged cheeses", "Tapas", "Aperitif"],
    price: 359,
  },
  {
    slug: "orange-wine-mini",
    name: "Orange Wine (Mini)",
    nameEs: "Vino Naranja 100 ML",
    category: "wine",
    image: "/products/vino-naranja-100ml.jpg",
    gallery: ["/products/vino-naranja-100ml.jpg", "/products/vino-naranja-100ml-cuadrada.jpg", "/products/vino-naranja-100-ml-2.jpg"],
    description: "The iconic Príncipe Azahar Orange Wine in a 100ml miniature, perfect for gifting, tasting, and curated collections.",
    longDescription: "The same exceptional Príncipe Azahar Orange Wine, beloved along Spain's Mediterranean coast, presented in an elegant 100ml miniature bottle. This format is ideal for luxury gift collections, tasting experiences, and curated gift boxes where presentation and discovery are part of the experience.",
    producer: "BSG · Bodegas Sendra González",
    origin: "Altea, Spain · 100ml",
    pairings: ["Gift collections", "Tasting experiences", "Seafood", "Tapas", "Aperitif"],
    price: 359,
  },

  // ── Spirits ───────────────────────────────────────────────────
  {
    slug: "matticello",
    name: "Matticello",
    nameEs: "Matticello",
    category: "spirits",
    image: "/products/matticello.jpg",
    description: "A distinctive Spanish cream liqueur from Altea. Served chilled or on the rocks. 500ml · 18% vol. Product of Spain.",
    longDescription: "Matticello is a unique Spanish cream liqueur produced by Bodegas Sendra González in Altea, elegant, smooth, and distinctively Mediterranean. Presented in a striking matte black bottle with the iconic Príncipe Azahar crest, Matticello is served very cold or on the rocks. Its rich, creamy character makes it exceptional as a dessert drink, a gifting statement, or a sophisticated after-dinner experience. 500ml · 18% vol.",
    producer: "Bodegas Sendra González",
    origin: "Altea, Spain · 500ml · 18% vol.",
    pairings: ["After dinner", "On the rocks", "Dessert pairing", "Coffee", "Fine chocolate"],
    price: 42,
  },
];

export const giftBoxes: Product[] = [
  {
    slug: "olive-oils-gift-box",
    name: "Exclusive Olive Oils Gift Box",
    nameEs: "Caja Exclusiva de Aceites de Oliva",
    category: "gift-boxes",
    image: "/products/aceite-ajo.jpg",
    description: "A curated selection of our finest artisan extra virgin olive oils from Altea, Spain. Perfect for the discerning palate.",
    longDescription: "Our Olive Oils Gift Box brings together a handpicked selection of Príncipe Azahar's premium infused extra virgin olive oils — garlic, chili, lemon, and rosemary — cold-pressed from hand-harvested Spanish olives. Presented in a signature gift box with a personal note. A sophisticated gift for executives, clients, and partners who appreciate the finest things.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Bread", "Salads", "Grilled meats", "Pasta", "Seafood"],
    price: 159,
  },
  {
    slug: "salts-gift-box",
    name: "Exclusive Salts Gift Box",
    nameEs: "Caja Exclusiva de Sales Gourmet",
    category: "gift-boxes",
    image: "/products/sal-rosa.jpg",
    description: "A stunning collection of artisan gourmet salts from Spain's finest salt flats. An extraordinary gift for any occasion.",
    longDescription: "The Salts Gift Box features a curated selection of Príncipe Azahar's artisan sea salts — from delicate pink Himalayan to bold smoked varieties — each harvested and finished with the same care that defines Spanish culinary tradition. Beautifully packaged in a premium gift box with your personal message enclosed. The gift that elevates every meal.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Steak", "Seafood", "Vegetables", "Chocolate", "Desserts"],
    price: 79,
  },
  {
    slug: "vinegars-gift-box",
    name: "Exclusive Vinegars Gift Box",
    nameEs: "Caja Exclusiva de Vinagres Gourmet",
    category: "gift-boxes",
    image: "/products/vinagre-vainilla.jpg",
    description: "A refined collection of aged artisan vinegars from Altea — vanilla, orange, pomegranate, and more. Rare and remarkable.",
    longDescription: "The Vinegars Gift Box showcases the breadth of Príncipe Azahar's award-winning artisan vinegar collection. Aged in oak barrels and infused with botanicals unique to Spain's Mediterranean coast — vanilla, orange blossom, pomegranate, and fig — these vinegars are unlike anything available in the US market. A truly memorable gift for the sophisticated executive or culinary enthusiast.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Salads", "Charcuterie", "Cheese", "Oysters", "Desserts"],
    price: 159,
  },
  {
    slug: "wines-gift-box",
    name: "Exclusive Wines Gift Box",
    nameEs: "Caja Exclusiva de Vinos Premium",
    category: "gift-boxes",
    image: "/products/vino-naranja.jpg",
    description: "Our signature orange wine collection from Altea — Spain's best-kept secret. An extraordinary conversation-starting gift.",
    longDescription: "The Wines Gift Box showcases Príncipe Azahar's celebrated orange wine — a natural, skin-contact white wine made from indigenous Spanish varietals along the Costa Blanca. Vibrant amber in color with notes of dried apricot, honey, and toasted almonds, this wine is unlike anything your recipient has tasted. Includes both the 500ml reserve and the elegant 100ml mini — perfect for gifting executives, VIP clients, and hospitality leaders.",
    producer: "Príncipe Azahar · Bodegas Sendra González",
    origin: "Altea, Spain",
    pairings: ["Charcuterie", "Aged cheese", "Sushi", "Grilled fish", "Oysters"],
    price: 279,
  },
];

export const categories = [
  { slug: "all",         label: "All Products" },
  { slug: "gift-boxes",  label: "Gift Boxes" },
  { slug: "olive-oils",  label: "Olive Oils" },
  { slug: "salts",       label: "Salts" },
  { slug: "vinegars",    label: "Vinegars" },
  { slug: "wine",        label: "Orange Wine" },
  { slug: "spirits",     label: "Spirits" },
];
